### ISSUE TITLE
模板工程头文件路径问题

### ISSUE THREAD

**Issue by afshare** [Neutree/STM32f103DriverLib#1]
## __模板工程没有把所有的头文件路径都包含进去，导致使用的时候，添加了头文件却找不到。建议改一下模板工程。__

使用姿势：打开模板工程，添加esp8266功能的时候。

**Comment by Neutree** [comment]
啊哈，可以的

**Comment by afshare** [comment]
就是MDK里面Options菜单，C/C++标签Include Paths里面耶，模板工程没有把所有头文件路径加进去。
